#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.install_profil = "minimal"
    args.language = "fr"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    #test_upgrade_from.bc57252858ce9402412ecccf82de2c2e2be67294.name = "Upgrade from 9.4.6~ynh2"
    test_upgrade_from.64f92590358018ffa8d0d71e6d6b3a158a82423e.name = "Upgrade from 2024.07.03~ynh1"
